name: Generate Shop Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes (UTC)
  workflow_dispatch:       # Allow manual trigger

jobs:
  generate-shop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (no default token)
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git remote with PUSH_TOKEN
        env:
          TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git

      - name: Log UTC timestamp
        run: date -u

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install --upgrade pip discord.py

      - name: Generate shop
        run: python generate_shop.py "${{ secrets.SECRET_KEY }}" eggs.csv

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add shop.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update shop.json [CI]"
            git push origin HEAD:main
          fi

      - name: Announce shop on Discord
        if: success()
        env:
          DISCORD_BOT_TOKEN:   ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CHANNEL_ID:  ${{ secrets.DISCORD_CHANNEL_ID }}
          ROLE_SLIMEEGG:       ${{ secrets.ROLE_SLIMEEGG }}
          ROLE_ROCKEGG:        ${{ secrets.ROLE_ROCKEGG }}
          ROLE_BISMUTHEGG:     ${{ secrets.ROLE_BISMUTHEGG }}
          ROLE_MAGMAEGG:       ${{ secrets.ROLE_MAGMAEGG }}
        run: python post_shop_to_discord.py
