name: Generate Shop Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes
  workflow_dispatch:       # Also allows manual trigger

jobs:
  generate-shop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies (if needed)
        run: pip install --upgrade pip

      - name: Generate shop
        run: python generate_shop.py "${{ secrets.SECRET_KEY }}" eggs.csv

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add shop.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update shop.json [CI]"
            git push
          fi
